/**
 * Cropped Bolognia line-art (TABLE 3.1 primary lesions) per morphology.
 * Source panels: https://plasticsurgerykey.com/lesional-morphology-and-assessment/
 * (Bolognia et al., Dermatology 3e — reproduced on Plastic Surgery Key).
 *
 * PNGs under assets/bolognia-crops/ are generated by scripts/crop_bolognia_diagrams.py
 */
(function () {
  window.PSK_REFERENCE = {
    diagramPathForId(id) {
      const slug = typeof id === "string" ? id.toLowerCase() : "_default";
      return `assets/bolognia-crops/${slug}.png`;
    },
    defaultDiagramPath: "assets/bolognia-crops/_default.png",
    sourcePage: "https://plasticsurgerykey.com/lesional-morphology-and-assessment/",
    credit:
      "Line drawings: Bolognia JL, Jorizzo JL, Rapini RP, eds. Dermatology. 3rd ed. St. Louis: Saunders; 2012. Figure via Plastic Surgery Key (cropped to lesion diagram).",
  };

  window.getMorphologyDiagramDataUrl = function (id) {
    return window.PSK_REFERENCE.diagramPathForId(id);
  };
})();
