/**
 * Line-drawing crops per morphology (assets under assets/bolognia-crops/ for path stability).
 * PNGs are generated by scripts/crop_bolognia_diagrams.py
 */
(function () {
  window.PSK_REFERENCE = {
    diagramPathForId(id) {
      const slug = typeof id === "string" ? id.toLowerCase() : "_default";
      return `assets/bolognia-crops/${slug}.png`;
    },
    defaultDiagramPath: "assets/bolognia-crops/_default.png",
    credit: "Line drawings for morphologic reference.",
  };

  window.getMorphologyDiagramDataUrl = function (id) {
    return window.PSK_REFERENCE.diagramPathForId(id);
  };
})();
